name: Deploy Delta to DevAgent1

on:
  push:
    branches:
      - devagent1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate Salesforce
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias devagent1

      - name: Install SGD
        run: |
          echo y | sf plugins install sfdx-git-delta

      - name: Generate Delta
        run: |
          mkdir delta

          sf sgd source delta \
            --from HEAD~1 \
            --to HEAD \
            --generate-delta \
            --output-dir delta

      - name: Deploy Delta
        run: |
          sf project deploy start \
            --manifest delta/package/package.xml \
            --target-org devagent1
